<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Identity\CreatorAnalytics.Identity\CreatorAnalytics.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\Integration\CreatorAnalytics.Integration\CreatorAnalytics.Integration.csproj" />
    <ProjectReference Include="..\..\Modules\Strategy\CreatorAnalytics.Strategy\CreatorAnalytics.Strategy.csproj" />
  </ItemGroup>

</Project>
