// <auto-generated />
using System;
using CreatorAnalytics.Strategy.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreatorAnalytics.Strategy.Infrastructure.Migrations
{
    [DbContext(typeof(StrategyDbContext))]
    [Migration("20261001223138_AddRowVersionToStrategyDocument")]
    partial class AddRowVersionToStrategyDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("strategy")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("StrategyDocuments", "strategy");
                });

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StrategyDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StrategyDocumentId");

                    b.HasIndex("TenantId");

                    b.ToTable("StrategyReviews", "strategy");
                });

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StrategyDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("StrategyDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("StrategyRevisions", "strategy");
                });

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyReview", b =>
                {
                    b.HasOne("CreatorAnalytics.Strategy.Domain.StrategyDocument", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StrategyDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyRevision", b =>
                {
                    b.HasOne("CreatorAnalytics.Strategy.Domain.StrategyDocument", null)
                        .WithMany("Revisions")
                        .HasForeignKey("StrategyDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorAnalytics.Strategy.Domain.StrategyDocument", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
